version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: data_tables 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
    - pgadmin_data:/var/lib/pgadmin

    ports:
      - "8081:80"
    depends_on:
      - postgres


  my_app:
    build: .
    container_name: lim_validation_pipeline
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql+psycopg2://user:password@postgres:5432/data_tables
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/app
volumes:
    postgres_data:
    pgadmin_data:

